### ISSUE TITLE
Replacing the integrated player

### ISSUE THREAD

**Issue by yuroyami** [yuroyami/syncplay-android#42]
Syncplay Android currently relies on Google's ExoPlayer to play media. On some devices, some formats may not be supported, some other devices are slow and are inefficient using Software Acceleration. 

To make sure all formats are supported and Hardware Acceleration is supported, Syncplay Android can use other integral players such as libVLC, IJK Player...etc

These players are built upon FFmpeg, which means all decoding is done natively.

**Pros**:
- Hardware Acceleration would be supported.
- All media formats would be supported.
- Reading from some raw streams would be made possible.

**Cons**: 
- Increased app size by about 60 MBs for libVLC and 20 MBs for IJK Player.
- Less stable and controllable player.

**Workarounds**:
To overcome the app size issue, I might resort to some peculiar measures:
- Deploying different flavors for the APK, one that uses ExoPlayer, one for libVLC, and one for IJKPlayer. These flavors will be named for instance: ```syncplay-android-Vx.x.x-exo.apk``` etc.

- Use one APK, but allow the user to download playera as plugins (downloadable at runtime)

Surely, the latter is tougher to implement. I might come around to using the first option. I would have to wrap the syncplay player in a factory class that returns a unified player which simulates all players without ambiguity.

This would be a nice touch since official Syncplay supports multiple players, that are capable of multiple different things.

**Comment by b0s-at-works** [comment]
What about MXPlayer? Sorry if it does not have implementation for integration. Just came to me...
I think MXPlyer one of the best players in the world for mobile devices

**Comment by Reddnek** [comment]
@b0s-at-works As far as I've heard, MXPlayer uses IJKPlayer under the hood, it's basically a media playback library that wraps FFmpeg (which plays all formats at ease) whilst ExoPlayer (which is used by Syncplay) only plays what the Android device's codecs internally support.

But, a MXPlayer-like Syncplay can be made possible if I integrate the FFmpeg library into it. That way, it can support all formats. When that's done, Syncplay Android will be available in two flavors, the Lite version (which is the current one), and a FFmpeg version that is less stable but plays all formats.

**Comment by soredake** [comment]
Just discovered that syncplay-android does not use hardware decoding for vp9 on my old tablet :(

**Comment by yuroyami** [comment]
Added mpv in [version (0.12.0)](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0)
