### ISSUE TITLE
Subtitle text outline

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-android#49]
It would be nice if syncplay can have settings for subtitle text outline to make it easier to read, like in mpv for example.

Example of outline from mpv:
![Снимок экрана 2023-02-07 171121](https://user-images.githubusercontent.com/5204968/217285090-489b5a22-1561-4267-9e03-f6f264e944ba.png)

**Comment by Reddnek** [comment]
Subtitles will be fully customizable in the next update. It's already in the works

**Comment by soredake** [comment]
@Reddnek thanks!

**Comment by yuroyami** [comment]
Added in [version (0.12.0)](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0) when using mpv.
