### ISSUE TITLE
Large files in playlist have incorrect size

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-android#52]
I've tested 6/12 gb files and they all have 2147.483647 MBs size
![Снимок экрана 2023-02-25 145017](https://user-images.githubusercontent.com/5204968/221357726-44cef4c6-b24f-4c6e-866d-4eafdac286fb.png)

**Comment by yuroyami** [comment]
Interesting. I will see what I can do about it

**Comment by yuroyami** [comment]
@soredake Although this is an unfortunate Android limitation, I attempted a workaround in the latest [version (0.12.0)](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0) which should be able to retrieve the correct file size for files exceeding 2 GBs. Test it and let me know.

**Comment by soredake** [comment]
@yuroyami seems to work correctly for now, thanks!
