### ISSUE TITLE
"Set as ready first-hand" is not working

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-android#57]
After joining the room i see myself as not ready in user list.

**Comment by yuroyami** [comment]
Fixed in [version (0.12.0)](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0).

**Comment by yuroyami** [comment]
I guess the issue often stuck around even after v0.12.0, this should be fixed for good as of [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0)
