### ISSUE TITLE
mobile phone playback url error

### ISSUE THREAD

**Issue by Zhaodaidai** [yuroyami/syncplay-android#63]
![image](https://user-images.githubusercontent.com/71388480/235624988-8e2bee18-3dec-4a14-b134-65d5b4157ddb.png)
My phone system is Android 13

**Comment by yuroyami** [comment]
I couldn't reproduce the issue. Could you provide more information ? and preferably the used URL as well if possible

**Comment by Zhaodaidai** [comment]
sure  Here is the play link
http://152.136.126.189:5244/d/God/%E9%98%BF%E9%87%8C%E4%BA%91/NAS/%E5%BD%B1%E8%A7%86/%E7%95%AA%E5%89%A7/%E7%BB%88%E6%9C%AB%E7%9A%84%E5%A5%B3%E6%AD%A6%E7%A5%9E/01.mp4

**Comment by yuroyami** [comment]
Indeed, the video doesn't play and it throws an error, I will debug the issue later and see what's wrong with it. I think it's because the link contains HTML-encoded Unicode characters. Thank you for the link!

**Comment by Zhaodaidai** [comment]
okay, don't worry, please

**Comment by yuroyami** [comment]
After troubleshooting, this seems to be an issue with the url itself. As you can see, the old url has "HTTP" protocol, but it redirects to "HTTPS" protocol url : 

[old link, has HTTP protocol](http://152.136.126.189:5244/d/God/%E9%98%BF%E9%87%8C%E4%BA%91/NAS/%E5%BD%B1%E8%A7%86/%E7%95%AA%E5%89%A7/%E7%BB%88%E6%9C%AB%E7%9A%84%E5%A5%B3%E6%AD%A6%E7%A5%9E/01.mp4)

[New link, it has HTTPS protocol](https://cn-beijing-data.aliyundrive.net/vfhttnr9%2F2218077%2F60cd51b1fed057bd82e94745a4aabbf500e4cd9e%2F60cd51b14c6fb17c05314516a1bb895d6b06e9e2?di=bj29&dr=1241607&f=60e5b7e3ea78cf7271794373b2953889a166f4a6&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%2701.mp4&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fyOovVvYVH0%2FeyTFfns3gUSLZGiZfaszz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNX3BQVHAqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABHNoeCrkyDLYRbP4dDvYUYQj1%2B3f75QRsHm3VrIXl4fnBr7BjzQQpnMvoWSrTtkKeo7ye3ECiAME%2B6b1254I4xDD3JmzOh1vpMKBVBMMmzLQP%2Bgnf3alflunFqi7C8lClv1VvSR5Y%2FI8hxqM3l2eD%2F8UzWpSP02VfZ%2BTBsHeMX3s%3D&u=0e601283ef5144e199b48cfe068f67c3&x-oss-access-key-id=STS.NTGq1aPZfd5YNqVWxAD9jfRqQ&x-oss-expires=1683344160&x-oss-signature=CG8lv39xFV2bQd6Kw07tv1aAmec%2FoGcMMvDZL6Nsuck%3D&x-oss-signature-version=OSS2)

Unfortunately, there is no way to fix this, you have to explicitly give syncplay the final link without any cross-protocol redirects (it can only redirect from https to https or from http to http...etc)

So if your URL has redirectors from HTTPS to HTTP or from HTTP to HTTPS, it will throw an error.
